set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'jiangmiao/auto-pairs'
Plugin 'fatih/vim-go'
Plugin 'vim-scripts/AutoComplPop'
call vundle#end()
filetype plugin indent on

set autowrite

" Go syntax highlighting
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1

" Auto formatting and importing
let g:go_fmt_autosave = 1
let g:go_fmt_command = "goimports"

autocmd vimenter * ++nested colorscheme gruvbox

set number 			" Display line numbers beside buffer
set nocompatible		" Don't maintain compatibility with Vi
set hidden			" Allow buffer change w/o saving
set lazyredraw			" Don't update while executing marcros
set backspace=indent,eol,start	" Sane backsapce behavior
set history=1000		" Remember last 1000 commands
set scrolloff=4			" Keep at least 4 lines below cursor

syntax on

